### ISSUE TITLE
ERROR: package installation failed   R-4.0.2

### ISSUE THREAD

**Issue by geng-lee** [sjessa/cytokit#88]
> devtools::install_github("sjessa/cytokit", build_vignettes = TRUE)
Downloading GitHub repo sjessa/cytokit@HEAD
✓  checking for file ‘/private/var/folders/dt/28pq17xj39l_1db6nc658kfc0000gn/T/Rtmpi1Jtmb/remotes46ba539bf7a2/sjessa-cytokit-819e467/DESCRIPTION’ (427ms)
─  preparing ‘cytokit’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes (362ms)
         -----------------------------------
─  installing *source* package ‘cytokit’ ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** byte-compile and prepare package for lazy loading
   错误: class "seurat" is not exported by 'namespace:Seurat'
   停止执行
   ERROR: lazy loading failed for package ‘cytokit’
─  removing ‘/private/var/folders/dt/28pq17xj39l_1db6nc658kfc0000gn/T/RtmpF46f8p/Rinst476e4412e990/cytokit’
         -----------------------------------
   ERROR: package installation failed
错误: Failed to install 'cytokit' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** R
E> ** data
E> *** moving datasets to lazyload DB
E> ** byte-compile and prepare package for lazy loading
E> 错误: class "seurat" is not exported by 'namespace:Seurat'
E> 停止执行
E> ERROR: lazy loading failed for package ‘cytokit’
E> * removing ‘/private/var/folders/dt/28pq17xj39l_1db6nc658kfc0000gn/T/RtmpF46f8p/Rinst476e4412e990/cytokit’
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by sjessa** [comment]
Hello! Thanks for checking out our package! As I mentioned in the README, this package is no longer being developed or maintained, please check out the newest version, cytobox at https://github.com/fungenomics/cytobox. Note that it currently works with Seurat v2.3.3, in order to maintain compatibility with existing functionality, but we are currently working on updating the package to work with Seurat v3. Thank you!
